"use client";

import dynamic from 'next/dynamic';
import React from 'react';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const componentsRegistry: Record<string, React.ComponentType<any>> = {
  AntiGravityBento: dynamic(() => import('./demos/AntiGravityBento').then(m => m.AntiGravityBento), { ssr: false }),
  CliTerminal: dynamic(() => import('./demos/CliTerminal').then(m => m.CliTerminal), { ssr: false }),
  ChangelogCard: dynamic(() => import('./demos/ChangelogCard').then(m => m.ChangelogCard), { ssr: false }),
  SeedBurstButton: dynamic(() => import('./demos/SeedBurstButton').then(m => m.SeedBurstButton), { ssr: false }),
  RippleButton: dynamic(() => import('./demos/RippleButton').then(m => m.RippleButton), { ssr: false }),
  MagneticNav: dynamic(() => import('./demos/MagneticNav').then(m => m.MagneticNav), { ssr: false }),
  BreadcrumbTrail: dynamic(() => import('./demos/BreadcrumbTrail').then(m => m.BreadcrumbTrail), { ssr: false }),
  RindPeelCard: dynamic(() => import('./demos/RindPeelCard').then(m => m.RindPeelCard), { ssr: false }),
  FlipCard: dynamic(() => import('./demos/FlipCard').then(m => m.FlipCard), { ssr: false }),
  VineInput: dynamic(() => import('./demos/VineInput').then(m => m.VineInput), { ssr: false }),
  TagInput: dynamic(() => import('./demos/TagInput').then(m => m.TagInput), { ssr: false }),
  ParticleBackground: dynamic(() => import('./demos/ClientParticleBackground').then(m => m.ParticleBackground), { ssr: false }),
  StickerWall: dynamic(() => import('./demos/ClientStickerWall').then(m => m.StickerWall), { ssr: false }),
  LuminousWaves: dynamic(() => import('./demos/ClientLuminousWaves').then(m => m.LuminousWaves), { ssr: false }),
  RetroGrid: dynamic(() => import('./demos/ClientRetroGrid').then(m => m.RetroGrid), { ssr: false }),
  NoiseBlob: dynamic(() => import('./demos/ClientNoiseBlob').then(m => m.NoiseBlob), { ssr: false }),
  MatrixRain: dynamic(() => import('./demos/ClientMatrixRain').then(m => m.MatrixRain), { ssr: false }),
  JuicyCursor: dynamic(() => import('./demos/JuicyCursor').then(m => m.JuicyCursor), { ssr: false }),
  CrosshairCursor: dynamic(() => import('./demos/CrosshairCursor').then(m => m.CrosshairCursor), { ssr: false }),
  HarvestReveal: dynamic(() => import('./demos/HarvestReveal').then(m => m.HarvestReveal), { ssr: false }),
  ParallaxStrips: dynamic(() => import('./demos/ParallaxStrips').then(m => m.ParallaxStrips), { ssr: false }),
  MelonDripText: dynamic(() => import('./demos/MelonDripText').then(m => m.MelonDripText), { ssr: false }),
  ScrambleText: dynamic(() => import('./demos/ScrambleText').then(m => m.ScrambleText), { ssr: false }),
  RindWipeTransition: dynamic(() => import('./demos/RindWipeTransition').then(m => m.RindWipeTransition), { ssr: false }),
  MorphTransition: dynamic(() => import('./demos/MorphTransition').then(m => m.MorphTransition), { ssr: false }),
  HoloTicket: dynamic(() => import('./demos/HoloTicket').then(m => m.HoloTicket), { ssr: false }),
  SolarCarousel: dynamic(() => import('./demos/SolarCarousel').then(m => m.SolarCarousel), { ssr: false }),
  KineticMagnet: dynamic(() => import('./demos/KineticMagnet').then(m => m.KineticMagnet), { ssr: false }),
  MorphingCyberNode: dynamic(() => import('./demos/MorphingCyberNode').then(m => m.MorphingCyberNode), { ssr: false }),
  OrbitalCommandRing: dynamic(() => import('./demos/OrbitalCommandRing').then(m => m.OrbitalCommandRing), { ssr: false }),
  KineticGlassGrid: dynamic(() => import('./demos/KineticGlassGrid').then(m => m.KineticGlassGrid), { ssr: false }),
  SignalLoom: dynamic(() => import('./demos/SignalLoom').then(m => m.SignalLoom), { ssr: false }),
  ChromaticMeltText: dynamic(() => import('./demos/ChromaticMeltText').then(m => m.ChromaticMeltText), { ssr: false }),
  RindScannerText: dynamic(() => import('./demos/RindScannerText').then(m => m.RindScannerText), { ssr: false }),
  StickerStackText: dynamic(() => import('./demos/StickerStackText').then(m => m.StickerStackText), { ssr: false }),
  GlyphOrbitText: dynamic(() => import('./demos/GlyphOrbitText').then(m => m.GlyphOrbitText), { ssr: false }),
  SeedwaveText: dynamic(() => import('./demos/SeedwaveText').then(m => m.SeedwaveText), { ssr: false }),
  FloatingOrbs: dynamic(() => import('./demos/FloatingOrbs').then(m => m.FloatingOrbs), { ssr: false }),
  GlitchPulseCore: dynamic(() => import('./demos/GlitchPulseCore').then(m => m.GlitchPulseCore), { ssr: false }),
  MagneticParticleField: dynamic(() => import('./demos/MagneticParticleField').then(m => m.MagneticParticleField), { ssr: false }),
  RetroCrtBackground: dynamic(() => import('./demos/RetroCrtBackground').then(m => m.RetroCrtBackground), { ssr: false }),
  StickerCollageWall: dynamic(() => import('./demos/StickerCollageWall').then(m => m.StickerCollageWall), { ssr: false }),
  HyperMorphBento: dynamic(() => import('./demos/HyperMorphBento').then(m => m.HyperMorphBento), { ssr: false }),
  QuantumLensDecoder: dynamic(() => import('./demos/QuantumLensDecoder').then(m => m.QuantumLensDecoder), { ssr: false }),
  InfinityMirrorCard: dynamic(() => import('./demos/InfinityMirrorCard').then(m => m.InfinityMirrorCard), { ssr: false }),
  ElasticTetherHub: dynamic(() => import('./demos/ElasticTetherHub').then(m => m.ElasticTetherHub), { ssr: false }),
  FluidMagneticDial: dynamic(() => import('./demos/FluidMagneticDial').then(m => m.FluidMagneticDial), { ssr: false }),
  SynapseTerminal: dynamic(() => import('./demos/SynapseTerminal').then(m => m.SynapseTerminal), { ssr: false }),
  KineticShardTerminal: dynamic(() => import('./demos/KineticShardTerminal').then(m => m.KineticShardTerminal), { ssr: false }),
  KineticHoloStack: dynamic(() => import('./demos/KineticHoloStack').then(m => m.KineticHoloStack), { ssr: false }),
  KineticShatterCard: dynamic(() => import('./demos/KineticShatterCard').then(m => m.KineticShatterCard), { ssr: false }),
  ChromaticSliceCard: dynamic(() => import('./demos/ChromaticSliceCard').then(m => m.ChromaticSliceCard), { ssr: false }),
  LiquidDimensionalNav: dynamic(() => import('./demos/LiquidDimensionalNav').then(m => m.LiquidDimensionalNav), { ssr: false }),
  NexusPromptCore: dynamic(() => import('./demos/NexusPromptCore').then(m => m.NexusPromptCore), { ssr: false }),
  PrismVault: dynamic(() => import('./demos/PrismVault').then(m => m.PrismVault), { ssr: false }),
  TerminalCursor: dynamic(() => import('./demos/TerminalCursor').then(m => m.TerminalCursor), { ssr: false }),
  CyberBiometricScanner: dynamic(() => import('./demos/CyberBiometricScanner').then(m => m.CyberBiometricScanner), { ssr: false }),
  HoloDeployCard: dynamic(() => import('./demos/HoloDeployCard').then(m => m.HoloDeployCard), { ssr: false }),
  HoloHexagonMap: dynamic(() => import('./demos/HoloHexagonMap').then(m => m.HoloHexagonMap), { ssr: false }),
  HoloSealVault: dynamic(() => import('./demos/HoloSealVault').then(m => m.HoloSealVault), { ssr: false }),
  HyperDriveWidget: dynamic(() => import('./demos/HyperDriveWidget').then(m => m.HyperDriveWidget), { ssr: false }),
  KineticSwingTag: dynamic(() => import('./demos/KineticSwingTag').then(m => m.KineticSwingTag), { ssr: false }),
  NeuralPatternLock: dynamic(() => import('./demos/NeuralPatternLock').then(m => m.NeuralPatternLock), { ssr: false }),
  SingularityControlNode: dynamic(() => import('./demos/SingularityControlNode').then(m => m.SingularityControlNode), { ssr: false }),
  TactileIDCard: dynamic(() => import('./demos/TactileIDCard').then(m => m.TactileIDCard), { ssr: false }),
  TetheredOrbitalVault: dynamic(() => import('./demos/TetheredOrbitalVault').then(m => m.TetheredOrbitalVault), { ssr: false }),
  VoidPortalReveal: dynamic(() => import('./demos/VoidPortalReveal').then(m => m.VoidPortalReveal), { ssr: false }),
  ZeroGravityShards: dynamic(() => import('./demos/ZeroGravityShards').then(m => m.ZeroGravityShards), { ssr: false }),
};
