"use client";

import dynamic from 'next/dynamic';
import React from 'react';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const componentsRegistry: Record<string, React.ComponentType<any>> = {
  AntiGravityBento: dynamic(() => import('./demos/AntiGravityBento').then(m => m.AntiGravityBento), { ssr: false }),
  CliTerminal: dynamic(() => import('./demos/CliTerminal').then(m => m.CliTerminal), { ssr: false }),
  ChangelogCard: dynamic(() => import('./demos/ChangelogCard').then(m => m.ChangelogCard), { ssr: false }),
  SeedBurstButton: dynamic(() => import('./demos/SeedBurstButton').then(m => m.SeedBurstButton), { ssr: false }),
  RippleButton: dynamic(() => import('./demos/RippleButton').then(m => m.RippleButton), { ssr: false }),
  MagneticNav: dynamic(() => import('./demos/MagneticNav').then(m => m.MagneticNav), { ssr: false }),
  BreadcrumbTrail: dynamic(() => import('./demos/BreadcrumbTrail').then(m => m.BreadcrumbTrail), { ssr: false }),
  RindPeelCard: dynamic(() => import('./demos/RindPeelCard').then(m => m.RindPeelCard), { ssr: false }),
  FlipCard: dynamic(() => import('./demos/FlipCard').then(m => m.FlipCard), { ssr: false }),
  VineInput: dynamic(() => import('./demos/VineInput').then(m => m.VineInput), { ssr: false }),
  TagInput: dynamic(() => import('./demos/TagInput').then(m => m.TagInput), { ssr: false }),
  ParticleBackground: dynamic(() => import('./demos/ClientParticleBackground').then(m => m.ParticleBackground), { ssr: false }),
  StickerWall: dynamic(() => import('./demos/ClientStickerWall').then(m => m.StickerWall), { ssr: false }),
  LuminousWaves: dynamic(() => import('./demos/ClientLuminousWaves').then(m => m.LuminousWaves), { ssr: false }),
  RetroGrid: dynamic(() => import('./demos/ClientRetroGrid').then(m => m.RetroGrid), { ssr: false }),
  NoiseBlob: dynamic(() => import('./demos/ClientNoiseBlob').then(m => m.NoiseBlob), { ssr: false }),
  MatrixRain: dynamic(() => import('./demos/ClientMatrixRain').then(m => m.MatrixRain), { ssr: false }),
  JuicyCursor: dynamic(() => import('./demos/JuicyCursor').then(m => m.JuicyCursor), { ssr: false }),
  CrosshairCursor: dynamic(() => import('./demos/CrosshairCursor').then(m => m.CrosshairCursor), { ssr: false }),
  HarvestReveal: dynamic(() => import('./demos/HarvestReveal').then(m => m.HarvestReveal), { ssr: false }),
  ParallaxStrips: dynamic(() => import('./demos/ParallaxStrips').then(m => m.ParallaxStrips), { ssr: false }),
  MelonDripText: dynamic(() => import('./demos/MelonDripText').then(m => m.MelonDripText), { ssr: false }),
  ScrambleText: dynamic(() => import('./demos/ScrambleText').then(m => m.ScrambleText), { ssr: false }),
  RindWipeTransition: dynamic(() => import('./demos/RindWipeTransition').then(m => m.RindWipeTransition), { ssr: false }),
  MorphTransition: dynamic(() => import('./demos/MorphTransition').then(m => m.MorphTransition), { ssr: false }),
  TicketCard: dynamic(() => import('./demos/TicketCard').then(m => m.TicketCard), { ssr: false }),
  SolarCarousel: dynamic(() => import('./demos/SolarCarousel').then(m => m.SolarCarousel), { ssr: false }),
  MagneticPointerGrid: dynamic(() => import('./demos/MagneticPointerGrid').then(m => m.MagneticPointerGrid), { ssr: false }),
  MorphingControlNode: dynamic(() => import('./demos/MorphingControlNode').then(m => m.MorphingControlNode), { ssr: false }),
  OrbitalCommandRing: dynamic(() => import('./demos/OrbitalCommandRing').then(m => m.OrbitalCommandRing), { ssr: false }),
  ProximityGlassGrid: dynamic(() => import('./demos/ProximityGlassGrid').then(m => m.ProximityGlassGrid), { ssr: false }),
  ThreadRouteBoard: dynamic(() => import('./demos/ThreadRouteBoard').then(m => m.ThreadRouteBoard), { ssr: false }),
  ChromaticMeltText: dynamic(() => import('./demos/ChromaticMeltText').then(m => m.ChromaticMeltText), { ssr: false }),
  RindScannerText: dynamic(() => import('./demos/RindScannerText').then(m => m.RindScannerText), { ssr: false }),
  StickerStackText: dynamic(() => import('./demos/StickerStackText').then(m => m.StickerStackText), { ssr: false }),
  GlyphOrbitText: dynamic(() => import('./demos/GlyphOrbitText').then(m => m.GlyphOrbitText), { ssr: false }),
  SeedwaveText: dynamic(() => import('./demos/SeedwaveText').then(m => m.SeedwaveText), { ssr: false }),
  FloatingOrbs: dynamic(() => import('./demos/FloatingOrbs').then(m => m.FloatingOrbs), { ssr: false }),
  GlitchStatusIndicator: dynamic(() => import('./demos/GlitchStatusIndicator').then(m => m.GlitchStatusIndicator), { ssr: false }),
  MagneticParticleField: dynamic(() => import('./demos/MagneticParticleField').then(m => m.MagneticParticleField), { ssr: false }),
  RetroCrtBackground: dynamic(() => import('./demos/RetroCrtBackground').then(m => m.RetroCrtBackground), { ssr: false }),
  StickerCollageWall: dynamic(() => import('./demos/StickerCollageWall').then(m => m.StickerCollageWall), { ssr: false }),
  DynamicBentoLayout: dynamic(() => import('./demos/DynamicBentoLayout').then(m => m.DynamicBentoLayout), { ssr: false }),
  LensTextDecoder: dynamic(() => import('./demos/LensTextDecoder').then(m => m.LensTextDecoder), { ssr: false }),
  InfinityMirrorCard: dynamic(() => import('./demos/InfinityMirrorCard').then(m => m.InfinityMirrorCard), { ssr: false }),
  TetherNodeMenu: dynamic(() => import('./demos/TetherNodeMenu').then(m => m.TetherNodeMenu), { ssr: false }),
  FluidControlDial: dynamic(() => import('./demos/FluidControlDial').then(m => m.FluidControlDial), { ssr: false }),
  InteractiveGraphNetwork: dynamic(() => import('./demos/InteractiveGraphNetwork').then(m => m.InteractiveGraphNetwork), { ssr: false }),
  DataShardTerminal: dynamic(() => import('./demos/DataShardTerminal').then(m => m.DataShardTerminal), { ssr: false }),
  LayeredBlueprintStack: dynamic(() => import('./demos/LayeredBlueprintStack').then(m => m.LayeredBlueprintStack), { ssr: false }),
  ShatterOnHoverCard: dynamic(() => import('./demos/ShatterOnHoverCard').then(m => m.ShatterOnHoverCard), { ssr: false }),
  ChromaticSliceCard: dynamic(() => import('./demos/ChromaticSliceCard').then(m => m.ChromaticSliceCard), { ssr: false }),
  LiquidDimensionalNav: dynamic(() => import('./demos/LiquidDimensionalNav').then(m => m.LiquidDimensionalNav), { ssr: false }),
  NexusPromptCore: dynamic(() => import('./demos/NexusPromptCore').then(m => m.NexusPromptCore), { ssr: false }),
  PrismVault: dynamic(() => import('./demos/PrismVault').then(m => m.PrismVault), { ssr: false }),
  TerminalCursor: dynamic(() => import('./demos/TerminalCursor').then(m => m.TerminalCursor), { ssr: false }),
  BiometricTouchScanner: dynamic(() => import('./demos/BiometricTouchScanner').then(m => m.BiometricTouchScanner), { ssr: false }),
  UnfoldingPanelCard: dynamic(() => import('./demos/UnfoldingPanelCard').then(m => m.UnfoldingPanelCard), { ssr: false }),
  HexagonStatusGrid: dynamic(() => import('./demos/HexagonStatusGrid').then(m => m.HexagonStatusGrid), { ssr: false }),
  TearSecuritySeal: dynamic(() => import('./demos/TearSecuritySeal').then(m => m.TearSecuritySeal), { ssr: false }),
  HyperDriveWidget: dynamic(() => import('./demos/HyperDriveWidget').then(m => m.HyperDriveWidget), { ssr: false }),
  InteractiveSwingTag: dynamic(() => import('./demos/InteractiveSwingTag').then(m => m.InteractiveSwingTag), { ssr: false }),
  NeuralPatternLock: dynamic(() => import('./demos/NeuralPatternLock').then(m => m.NeuralPatternLock), { ssr: false }),
  SingularityControlNode: dynamic(() => import('./demos/SingularityControlNode').then(m => m.SingularityControlNode), { ssr: false }),
  TactileIDCard: dynamic(() => import('./demos/TactileIDCard').then(m => m.TactileIDCard), { ssr: false }),
  OrbitalKeyVault: dynamic(() => import('./demos/OrbitalKeyVault').then(m => m.OrbitalKeyVault), { ssr: false }),
  ThreeDPortalReveal: dynamic(() => import('./demos/ThreeDPortalReveal').then(m => m.ThreeDPortalReveal), { ssr: false }),
  ZeroGravityBentoGrid: dynamic(() => import('./demos/ZeroGravityBentoGrid').then(m => m.ZeroGravityBentoGrid), { ssr: false }),
  HologramProjector: dynamic(() => import('./demos/HologramProjector').then(m => m.HologramProjector), { ssr: false }),
  GyroscopeCore: dynamic(() => import('./demos/GyroscopeCore').then(m => m.GyroscopeCore), { ssr: false }),
  MagneticCard: dynamic(() => import('./demos/MagneticCard').then(m => m.MagneticCard), { ssr: false }),
  GlowTerminal: dynamic(() => import('./demos/GlowTerminal').then(m => m.GlowTerminal), { ssr: false }),
  VoidNexus: dynamic(() => import('./demos/VoidNexus').then(m => m.VoidNexus), { ssr: false }),
};
